/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutCallbackRouteImport } from './routes/logout-callback'
import { Route as LoginCallbackRouteImport } from './routes/login-callback'
import { Route as DesignSystemRouteRouteImport } from './routes/design-system/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignSystemIndexRouteImport } from './routes/design-system/index'
import { Route as DesignSystemTypographyRouteImport } from './routes/design-system/typography'
import { Route as DesignSystemSizingRouteImport } from './routes/design-system/sizing'
import { Route as DesignSystemComponentsRouteImport } from './routes/design-system/components'
import { Route as DesignSystemColorsRouteImport } from './routes/design-system/colors'

const LogoutCallbackRoute = LogoutCallbackRouteImport.update({
  id: '/logout-callback',
  path: '/logout-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/login-callback',
  path: '/login-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRouteRoute = DesignSystemRouteRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemIndexRoute = DesignSystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemTypographyRoute = DesignSystemTypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemSizingRoute = DesignSystemSizingRouteImport.update({
  id: '/sizing',
  path: '/sizing',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemComponentsRoute = DesignSystemComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemColorsRoute = DesignSystemColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRouteRouteWithChildren
  '/login-callback': typeof LoginCallbackRoute
  '/logout-callback': typeof LogoutCallbackRoute
  '/design-system/colors': typeof DesignSystemColorsRoute
  '/design-system/components': typeof DesignSystemComponentsRoute
  '/design-system/sizing': typeof DesignSystemSizingRoute
  '/design-system/typography': typeof DesignSystemTypographyRoute
  '/design-system/': typeof DesignSystemIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login-callback': typeof LoginCallbackRoute
  '/logout-callback': typeof LogoutCallbackRoute
  '/design-system/colors': typeof DesignSystemColorsRoute
  '/design-system/components': typeof DesignSystemComponentsRoute
  '/design-system/sizing': typeof DesignSystemSizingRoute
  '/design-system/typography': typeof DesignSystemTypographyRoute
  '/design-system': typeof DesignSystemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRouteRouteWithChildren
  '/login-callback': typeof LoginCallbackRoute
  '/logout-callback': typeof LogoutCallbackRoute
  '/design-system/colors': typeof DesignSystemColorsRoute
  '/design-system/components': typeof DesignSystemComponentsRoute
  '/design-system/sizing': typeof DesignSystemSizingRoute
  '/design-system/typography': typeof DesignSystemTypographyRoute
  '/design-system/': typeof DesignSystemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/login-callback'
    | '/logout-callback'
    | '/design-system/colors'
    | '/design-system/components'
    | '/design-system/sizing'
    | '/design-system/typography'
    | '/design-system/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login-callback'
    | '/logout-callback'
    | '/design-system/colors'
    | '/design-system/components'
    | '/design-system/sizing'
    | '/design-system/typography'
    | '/design-system'
  id:
    | '__root__'
    | '/'
    | '/design-system'
    | '/login-callback'
    | '/logout-callback'
    | '/design-system/colors'
    | '/design-system/components'
    | '/design-system/sizing'
    | '/design-system/typography'
    | '/design-system/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignSystemRouteRoute: typeof DesignSystemRouteRouteWithChildren
  LoginCallbackRoute: typeof LoginCallbackRoute
  LogoutCallbackRoute: typeof LogoutCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout-callback': {
      id: '/logout-callback'
      path: '/logout-callback'
      fullPath: '/logout-callback'
      preLoaderRoute: typeof LogoutCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-callback': {
      id: '/login-callback'
      path: '/login-callback'
      fullPath: '/login-callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system/': {
      id: '/design-system/'
      path: '/'
      fullPath: '/design-system/'
      preLoaderRoute: typeof DesignSystemIndexRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/typography': {
      id: '/design-system/typography'
      path: '/typography'
      fullPath: '/design-system/typography'
      preLoaderRoute: typeof DesignSystemTypographyRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/sizing': {
      id: '/design-system/sizing'
      path: '/sizing'
      fullPath: '/design-system/sizing'
      preLoaderRoute: typeof DesignSystemSizingRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components': {
      id: '/design-system/components'
      path: '/components'
      fullPath: '/design-system/components'
      preLoaderRoute: typeof DesignSystemComponentsRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/colors': {
      id: '/design-system/colors'
      path: '/colors'
      fullPath: '/design-system/colors'
      preLoaderRoute: typeof DesignSystemColorsRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
  }
}

interface DesignSystemRouteRouteChildren {
  DesignSystemColorsRoute: typeof DesignSystemColorsRoute
  DesignSystemComponentsRoute: typeof DesignSystemComponentsRoute
  DesignSystemSizingRoute: typeof DesignSystemSizingRoute
  DesignSystemTypographyRoute: typeof DesignSystemTypographyRoute
  DesignSystemIndexRoute: typeof DesignSystemIndexRoute
}

const DesignSystemRouteRouteChildren: DesignSystemRouteRouteChildren = {
  DesignSystemColorsRoute: DesignSystemColorsRoute,
  DesignSystemComponentsRoute: DesignSystemComponentsRoute,
  DesignSystemSizingRoute: DesignSystemSizingRoute,
  DesignSystemTypographyRoute: DesignSystemTypographyRoute,
  DesignSystemIndexRoute: DesignSystemIndexRoute,
}

const DesignSystemRouteRouteWithChildren =
  DesignSystemRouteRoute._addFileChildren(DesignSystemRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignSystemRouteRoute: DesignSystemRouteRouteWithChildren,
  LoginCallbackRoute: LoginCallbackRoute,
  LogoutCallbackRoute: LogoutCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
